cloud_nats_bridge:
  cloud_parameters:
    NATS_IP: "44.206.13.7" #change to amazon ec2 ipv4 address
    NATS_PORT: "4222"
    UNIT_ID: "cloud_id"
    UNIT_TYPE: "infrastructure"
    CARMA_CLOUD_LOG_DIR: "/opt/tomcat/logs" #/opt/tomcat/logs on deployed CC system
    CARMA_CLOUD_LOG_NAME: "carmacloud.log"
    LOG_LEVEL: "debug"
    LOG_NAME: "cloud_nats_bridge"
    LOG_PATH: "/tmp/logs/" 
    LOG_ROTATION_SIZE_BYTES: "2147483648" #2 gigabytes
    LOG_HANDLER: "file" #"console": Print logs on console; "file": Save logs to file; "file_and_console": Prints logs on console and file
    TCR_STRING: "TrafficControlRequest" #TCR string to search for in carma cloud log
    TCM_STRING: "TrafficControlMessage" #TCM string to search for in carma cloud log
