version: "3.4"
services:
  ros2-nats-bridge:
    build:
          context: ./telematic_units/carma_vehicle_bridge
          dockerfile: Dockerfile
    image: usdotfhwastoldev/carma_vehicle_bridge
    container_name: carma_vehicle_bridge
    network_mode: host
    entrypoint: /ws/ros_entrypoint.sh
    volumes:
           - ./logs:/var/logs
  
  streets-nats-bridge:
    build:
          context: ./telematic_units/carma_street_bridge
          dockerfile: Dockerfile
    image: usdotfhwastoldev/carma_street_bridge
    container_name: carma_street_bridge
    network_mode: host
    volumes:
           - ./logs:/var/logs
    environment:
    #console: Print logs on console; file: Save logs to file; both: Prints logs on console and file
    - LOG_HANDLER_TYPE=console