version: "3"
services:
  telematic_web_server:
      build:
        context: "./telematic_apps/web_app/server"
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "1"
      network_mode: host
      environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true
        - ALLOW_CLIENT_URL=https://cav-telematics.com
        - GRAFANA_HTPASSWORD=/opt/apache2/grafana_htpasswd
        - SESSION_TIMEOUT=3600
        - SECRET=my_secret_telematic_ui
        # Server port
        - PORT=9010
        # MYSQL DB credentials. Need to be replaced with actual MYSQL DB during deployment
        - DB_HOST=<DB_HOST>
        - DB_USER=<DB_USER>
        - DB_PASSWORD=<DB_PASSWORD>
        - GRAFANA_DB=<GRAFANA_DB>
        # File upload service settings
        - UPLOAD_DESTINATION=s3
        - UPLOAD_DESTINATION_PATH=/opt/telematics/upload
        - AWS_ACCESS_KEY_ID=
        - AWS_SECRET_KEY=
        - S3_BUCKET=
        - S3_REGION=us-east-2
        - UPLOAD_HTTP_PORT=9011
        - UPLOAD_TIME_OUT=3600000 # Milliseconds
        - UPLOAD_MAX_FILE_SIZE=21474836480 #20 GB
        - CONCURRENT_QUEUE_SIZE=5 
        - PART_SIZE=10485760 
        - NATS_SERVERS=localhost:4222
        - FILE_PROCESSING_SUBJECT=ui.file.procressing
      volumes:
        - /opt/apache2/grafana_htpasswd:/opt/apache2/grafana_htpasswd
        - /opt/telematics/upload:/opt/telematics/upload

  telematic_web_client:
    build:
      context: "./telematic_apps/web_app/client"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    depends_on:
      - telematic_web_server
    volumes:
      - ./web_client.production.env.js:/usr/share/nginx/html/env.js

  apache2:
    build:
      context: "./telematic_apps/apache2"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    environment:
      - CLIENT_LOCAL_URL=http://127.0.0.1:8082/
      - GRAFANA_LOCAL_URL=http://127.0.0.1:3000/
      - TOPICSERVICE_LOCAL_URL=<http://telematic-cloud-messaging-server-private-url:8080/>
      - UISERVICE_LOCAL_URL=http://127.0.0.1:9010/
      - UISERVICE_LOCAL_UPLOAD_URL=http://127.0.0.1:9011/
    depends_on:
      - grafana
      - telematic_web_client
      - telematic_web_server
    volumes:
      - /opt/apache2/grafana_htpasswd:/etc/apache2/grafana_htpasswd

  grafana:
    build:
      context: "./telematic_apps/grafana"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    volumes:
      - /opt/grafana/logs:/var/log/grafana
      - ./telematic_apps/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/provisioning:/home/grafana/conf/provisioning
      - /home/ubuntu/.aws/credentials:/usr/share/grafana/.aws/credentials
    user: "472" #grafana user id
