version: '3'
services:
  influxdb:
    image:  influxdb:${INFLUXDB_DEV_TAG} 
    container_name: influxdb-dev
    ports:
      - '8086:8086'
    # restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    environment:
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=${DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_DEV_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_DEV_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_DEV_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_DEV_ORG}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_DEV_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - /opt/influxdb2/data:/var/lib/influxdb2 # data directory
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    ports:
      - '3306:3306'
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - mysql-datavolume:/var/lib/mysql
secrets:
    mysql_password:
        file: ./secrets/mysql_password.txt
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt
volumes:
  mysql-datavolume: