version: "3.4"
services:
  ros2-nats-bridge:
    build:
          context: ./telematic_units/carma_vehicle_bridge
          dockerfile: Dockerfile
    image: usdotfhwastoldev/carma_vehicle_bridge
    container_name: carma_vehicle_bridge
    network_mode: host
    entrypoint: /ws/ros_entrypoint.sh
  
  streets-nats-bridge:
    build:
          context: ./telematic_units/carma_street_bridge
          dockerfile: Dockerfile
    image: usdotfhwastoldev/carma_street_bridge
    container_name: carma_street_bridge
    network_mode: host
    volumes:
           - ./logs:/var/logs
  
  cloud-nats-bridge:
    build:
          context: ./telematic_units/carma_cloud_bridge
          dockerfile: Dockerfile
    image: usdotfhwastoldev/carma_cloud_bridge
    container_name: carma_cloud_bridge
    network_mode: host
    volumes:
           - ./logs:/var/logs           
           - /opt/tomcat/logs:/opt/tomcat/logs
    environment:
      #"console": Print logs on console; "file": Save logs to file; "file_and_console": Prints logs on console and file
      - LOG_HANDLER_TYPE=console
