version: "3"
services:
  telematic_web_server:
      build:
        context: "./telematic_apps/web_app/server"
      restart: always
      depends_on:
        - grafana
      logging:
        options:
          max-size: "10m"
          max-file: "1"
      network_mode: host
      environment:
        - NODE_ENV=dev.comelopment
        - CHOKIDAR_USEPOLLING=true
        - ALLOW_CLIENT_URL=http://local.com
        - GRAFANA_HTPASSWORD=/opt/apache2/grafana_htpasswd
        - SESSION_TIMEOUT=3600
        - SECRET=my_secret_telematic_ui
        # Server port
        - PORT=9010
        # MYSQL DB credentials. Need to be replaced with actual MYSQL DB during deployment
        - DB_HOST=127.0.0.1
        - DB_USER=telematic
        - DB_PASSWORD=telematic
        - GRAFANA_DB=wfd_grafana
      volumes:
        - /opt/apache2/grafana_htpasswd:/opt/apache2/grafana_htpasswd

  telematic_web_client:
    build:
      context: "./telematic_apps/web_app/client"
      args:
        REACT_APP_MESSAGING_SERVER_URI: "http://topic-service.local.com"
        REACT_APP_WEB_SERVER_URI: "http://ui-service.local.com"
        REACT_APP_GRAFANA_URI: "http://grafana.local.com/grafana"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    # depends_on:
    #   - telematic_web_server

  apache2:
    build:
      context: "./telematic_apps/apache2"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    environment:
      - CLIENT_LOCAL_URL=http://127.0.0.1:8082/
      - GRAFANA_LOCAL_URL=http://127.0.0.1:3000/
      - TOPICSERVICE_LOCAL_URL=http://127.0.0.1:8080/
      - UISERVICE_LOCAL_URL=http://127.0.0.1:9010/
    depends_on:
      - grafana
      - telematic_web_client
      # - telematic_web_server
    volumes:
      - /opt/apache2/grafana_htpasswd:/etc/apache2/grafana_htpasswd

  grafana:
    build:
      context: "./telematic_apps/grafana"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    network_mode: host
    volumes:
      - /opt/grafana/logs:/var/log/grafana
      - ./telematic_apps/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/provisioning:/home/grafana/conf/provisioning
      - /home/ubuntu/.aws/credentials:/usr/share/grafana/.aws/credentials
    user: "472" #grafana user id
