version: "3.0"

services:
  nats:
    image: 'nats:2.7.3-alpine3.15'
    ports:
      - "8222:8222"
      - "4222:4222"
      - "6222:6222"

  api:
    build:
      context: "./api"
    entrypoint: ./api-server
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
      - "MYSQL_USER=*****"
      - "MYSQL_PASSWORD=*****"
      - "MYSQL_DATABASE=wfd"
      - "MYSQL_URI=*****"
    depends_on:
      - nats
    ports:
      - "8080:8080"

  worker:
    build:
      context: "./worker"
    entrypoint: ./worker
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
      - "MYSQL_USER=*****""
      - "MYSQL_PASSWORD=*****""
      - "MYSQL_DATABASE=wfd"
      - "MYSQL_URI=*****"
    depends_on:
      - nats
    ports:
      - "8181:8181"