export const UPLOAD_STATUS = {
  NA: "NA",
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  COMPLETED: "COMPLETED",
};

export const PROCESSING_STATUS = {
  NA: "NA",
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  COMPLETED: "COMPLETED",
};
