export const UPLOAD_STATUS = {
  UNKNOWN: "UNKNOWN",
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  COMPLETED: "COMPLETED",
};

export const PROCESSING_STATUS = {
  UNKNOWN: "UNKNOWN",
  IN_PROGRESS: "IN_PROGRESS",
  ERROR: "ERROR",
  COMPLETED: "COMPLETED",
};
