name: carma-vehicle-bridge

on:
  workflow_dispatch:
  push:
    branches:
      - "feature_gha"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_units/carma_vehicle_bridge/
          file: ./telematic_system/telematic_units/carma_vehicle_bridge/Dockerfile
          push: true
          tags: usdotfhwastoldev/carma_vehicle_nats_bridge:${{ github.ref_name }}

  sonar:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/carma-base:develop
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt -y install python3-coverage python3-pytest ros-foxy-rclpy
      - run: python3 -m pip install nats-py
      - run: source /opt/ros/foxy/setup.bash && python3 -m coverage run -m pytest
        shell: bash
      - run: python3 -m coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=usdot-fhwa-stol_cda-telematics
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.projectName=cda-telematics
            -Dsonar.organization=usdot-fhwa-stol
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.verbose=true
            -Dsonar.java.binaries=.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
