name: carma-streets-bridge

on:
  workflow_dispatch:
  push:
    branches:
      - "feature_gha"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_units/carma_street_bridge/
          file: ./telematic_system/telematic_units/carma_street_bridge/Dockerfile
          push: true
          tags: usdotfhwastoldev/carma_street_nats_bridge:${{ github.ref_name }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: /opt/carma/src/cda-telematics/telematic_system/telematic_units/carma_street_bridge/streets_nats_bridge/
          args: >
             -Dsonar.python.coverage.reportPaths=coverage.xml
             -Dsonar.tests=tests/
             -Dsonar.verbose=true
