name: Docker Hub build

on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "carma-system-*"

jobs:
  determine_docker_org_and_tag:
    runs-on: ubuntu-latest
    outputs:
      docker_organization: ${{ steps.docker-org-and-tag.outputs.docker_organization }}
      docker_image_tag: ${{ steps.docker-org-and-tag.outputs.docker_image_tag }}
    steps:
      - id: docker-org-and-tag
        uses: usdot-fhwa-stol/actions/docker-org-and-tag@main

  dockerhub-telematic-cloud-messaging:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_cloud_messaging/
          push: true
          tags: usdotfhwastoldev/telematic_cloud_messaging:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-carma-streets-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_units/carma_street_bridge/
          push: true
          tags: usdotfhwastoldev/carma_street_nats_bridge:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-carma-vehicle-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_units/carma_vehicle_bridge/
          push: true
          tags: usdotfhwastoldev/carma_vehicle_nats_bridge:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-carma-cloud-bridge:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_units/carma_cloud_bridge/
          push: true
          tags: usdotfhwastoldev/carma_cloud_nats_bridge:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-historical-data-processing:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_historical_data_processing/
          push: true
          tags: usdotfhwastoldev/telematic_historical_data_processing:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-web-server:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_apps/web_app/server
          push: true
          tags: usdotfhwastoldev/telematic_web_server:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-web-client:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_apps/web_app/client
          push: true
          tags: usdotfhwastoldev/telematic_web_client:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-apache2:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_apps/apache2
          push: true
          tags: usdotfhwastoldev/telematic_apache2:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-grafana:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_apps/grafana
          push: true
          tags: usdotfhwastoldev/telematic_grafana:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}

  dockerhub-telematic-local-apache2:
    needs: determine_docker_org_and_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Docker Image Metadata
        shell: bash
        id: docker-image-metadata
        run: |
          echo build_date=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) >> $GITHUB_OUTPUT
          echo vcs_ref=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./telematic_system/telematic_apps/apache2
          file: ./telematic_system/telematic_apps/apache2/local.Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_local_apache2:${{ github.ref_name }}
          build-args: |
            BUILD_DATE=${{ steps.docker-image-metadata.outputs.build_date }}
            VCS_REF=${{ steps.docker-image-metadata.outputs.vcs_ref }}
