name: Docker Hub build
on:
  push:
    branches:
      - "develop"
      - "master"
      - "release/*"

jobs:
  dockerhub-telematic-cloud-messaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_cloud_messaging/
          file: ./telematic_system/telematic_cloud_messaging/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_cloud_messaging:${{ github.ref_name }}

  dockerhub-carma-streets-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_units/carma_street_bridge/
          file: ./telematic_system/telematic_units/carma_street_bridge/Dockerfile
          push: true
          tags: usdotfhwastoldev/carma_street_nats_bridge:${{ github.ref_name }}

  dockerhub-carma-vehicle-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_units/carma_vehicle_bridge/
          file: ./telematic_system/telematic_units/carma_vehicle_bridge/Dockerfile
          push: true
          tags: usdotfhwastoldev/carma_vehicle_nats_bridge:${{ github.ref_name }}

  dockerhub-carma-cloud-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_units/carma_cloud_bridge/
          file: ./telematic_system/telematic_units/carma_cloud_bridge/Dockerfile
          push: true
          tags: usdotfhwastoldev/carma_cloud_nats_bridge:${{ github.ref_name }}

  dockerhub-telematic_historical_data_processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_historical_data_processing/
          file: ./telematic_system/telematic_historical_data_processing/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_historical_data_processing:${{ github.ref_name }}
    
  dockerhub-telematic-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/web_app/server
          file: ./telematic_system/telematic_apps/web_app/server/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_web_server:${{ github.ref_name }}
  
  dockerhub-telematic-web-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/web_app/client
          file: ./telematic_system/telematic_apps/web_app/client/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_web_client:${{ github.ref_name }}
    
  dockerhub-telematic-apache2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/apache2
          file: ./telematic_system/telematic_apps/apache2/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_apache2:${{ github.ref_name }} 
  
  dockerhub-telematic-grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/grafana
          file: ./telematic_system/telematic_apps/grafana/Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_grafana:${{ github.ref_name }} 

  dockerhub-telematic-local-apache2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/apache2
          file: ./telematic_system/telematic_apps/apache2/local.Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_local_apache2:${{ github.ref_name }} 
  
  dockerhub-telematic-local-messaging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_cloud_messaging/
          file: ./telematic_system/telematic_cloud_messaging/local.Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_local_messaging:${{ github.ref_name }}

  dockerhub-telematic-local-web-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_apps/web_app/server
          file: ./telematic_system/telematic_apps/web_app/server/local.Dockerfile
          push: true
          tags: usdotfhwastoldev/telematic_local_web_server:${{ github.ref_name }}