name: telematic-cloud-messaging

on:
  workflow_dispatch:
  push:
    branches:
      - "feature_gha"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./telematic_system/telematic_cloud_messaging/
          file: ./telematic_system/telematic_cloud_messaging/Dockerfile
          path: telematic_system/telematic_cloud_messaging/
          push: true
          tags: usdotfhwastoldev/telematic_cloud_messaging:${{ github.ref_name }}

  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ./telematic_system/telematic_cloud_messaging/
          mvn install -DskipTests
          mvn -e -X clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Pcoverage -Dsonar.projectKey=usdot-fhwa-stol_cda-telematics -Dsonar.projectName=cda-telematics -Dsonar.organization=usdot-fhwa-stol-1 -Dsonar.host.url=https://sonarcloud.io

